### ISSUE TITLE
missing featherlight.css

### ISSUE THREAD

**Issue by RLHawk1** [VividWeb/vivid_thumb_gallery#1]
When using "lightbox" as the zoomType, it tries to load assets/featherlight.css, but this file is not included in the package.

**Comment by RLHawk1** [comment]
Nevermind. This is fixed in the github repository. This error only exists in the version at https://www.concrete5.org/marketplace/addons/thumb-gallery/

**Comment by clarkwinkelmann** [comment]
Well, that's still something to mind ! I wanted to report the same thing because I downloaded the addon from the marketplace !

EDIT: hummmm, that's not fixed https://github.com/VividWeb/vivid_thumb_gallery/blob/master/blocks/vivid_thumb_gallery/controller.php#L150 + file does not exist in `assets`
